application:
  name: backend
  project: landr
  cloud_region: aws/us-east-2
databases:
  - type: postgresql
    version: '12'
    name: DMS
routers:
  - name: main
    routes:
      - application_name: backend
        paths:
          - /
